version: "3"

includes:
  os: ./task/Taskfile_{{OS}}.yml

tasks:
  shared:
    cmds:
      - task btop
      - task ghostty
      - task nvim
      - task tmux
      - task kitty
      - task openrgb
      - task scripts
      - task cargo:install
      - task zsh
  luna:
    cmds:
      - task os:all
      - task shared
  domum:
    cmds:
      - task os:all
      - task shared
  bat:
    cmds:
      - mkdir -p ~/.config/bat
      - stow -v -t ~/.config/bat bat
  btop:
    cmds:
      - mkdir -p ~/.config/btop
      - stow -v -t ~/.config/btop btop
  ghostty:
    cmds:
      - mkdir -p ~/.config/ghostty
      - stow -v -t ~/.config/ghostty ghostty
  kitty:
    cmds:
      - mkdir -p ~/.config/kitty
      - stow -v -t ~/.config/kitty kitty
  nvim:
    cmds:
      - mkdir -p ~/.config/nvim
      - stow -v -t ~/.config/nvim nvim
  openrgb:
    cmds:
      - mkdir -p ~/.config/OpenRGB
      - stow -v -t ~/.config/OpenRGB openrgb
  zsh:
    cmds:
      - mkdir -p ~/.config/zsh
      - stow -v -t ~/.config/zsh zsh
