version: "3"

includes:
  os: ./task/Taskfile_{{OS}}.yml

tasks:
  shared:
    cmds:
      - task btop
      - task ghostty
      - task nvim
      - task tmux
      - task kitty
      - task openrgb
      - task scripts
      - task cargo:install
      - task zsh
  luna:
    cmds:
      - task os:all
      - task shared
  domum:
    cmds:
      - task os:all
      - task shared
