version: "3"

includes:
  os: ./task/Taskfile_{{OS}}.yml

tasks:
  shared:
    cmds:
      - task btop
      - task ghostty
      - task nvim
      - task tmux
      - task kitty
      - task openrgb
      - task scripts
      - task cargo:install
      - task zsh
  luna:
    cmds:
      - task os:all
      - task shared
  domum:
    cmds:
      - task os:all
      - task shared
  bat:
    cmds:
      - mkdir -p ~/.config/bat
      - stow -v -t ~/.config/bat bat
  btop:
    cmds:
      - mkdir -p ~/.config/btop
      - stow -v -t ~/.config/btop btop
  cargo:install:
    cmds:
      - cargo install krabby
  ghostty:
    cmds:
      - mkdir -p ~/.config/ghostty
      - stow -v -t ~/.config/ghostty ghostty
  kitty:
    cmds:
      - mkdir -p ~/.config/kitty
      - stow -v -t ~/.config/kitty kitty
  nvim:
    cmds:
      - mkdir -p ~/.config/nvim
      - stow -v -t ~/.config/nvim nvim
  openrgb:
    cmds:
      - mkdir -p ~/.config/OpenRGB
      - stow -v -t ~/.config/OpenRGB openrgb
  scripts:
    cmds:
      - mkdir -p ~/.config/scripts
      - stow -v -t ~/.config/scripts scripts
  starship:
    cmds:
      - stow -v -t ~/.config starship
  wezterm:
    cmds:
      - mkdir -p ~/.config/wezterm
      - stow -v -t ~/.config/wezterm wezterm
      - touch ~/.config/wezterm/theme.bin
      - echo "dark" > ~/.config/wezterm/theme.bin
  tmux:
    cmds:
      - mkdir -p ~/.config/tmux
      - stow -v -t ~/.config/tmux tmux
  zsh:
    cmds:
      - mkdir -p ~/.config/zsh
      - stow -v -t ~/.config/zsh zsh
