{
  helium,
  noctalia,
  zen-browser,
  zed,
  pkgs,
  pkgs-stable,
  ...
}:

{
  imports = [
    ./godot.nix
    ./prism.nix
  ];

  environment.systemPackages = with pkgs; [
    pkgs-stable.bitwarden-desktop
    pkgs-stable.protonup-qt
    pkgs-stable.unityhub
    audacity
    bemoji
    bitmagnet
    blender
    blueman
    cider-2
    pkgs-stable.davinci-resolve
    dconf-editor
    dunst
    element-desktop
    flameshot
    furmark
    fuzzel
    gammastep
    ghostty
    gimp
    github-desktop
    gnome-tweaks
    grim
    guake
    pkgs-stable.handbrake
    haruna
    helium.packages.${pkgs.stdenv.hostPlatform.system}.default
    helvum
    heroic
    pkgs-stable.jetbrains.rider
    kdePackages.ark
    kdePackages.dolphin
    kdePackages.filelight
    kdePackages.kate
    kdePackages.okular
    libreoffice-qt6-fresh
    pkgs-stable.librewolf
    lutris
    lxqt.pavucontrol-qt
    sunshine
    mangohud
    nautilus
    nextcloud-client
    noctalia.packages.${pkgs.stdenv.hostPlatform.system}.default
    obs-studio
    obs-studio-plugins.wlrobs
    obsidian
    octaveFull
    onedrive
    openrgb-with-all-plugins
    pavucontrol
    phoronix-test-suite
    pinta
    pkgs-stable.qemu_full
    qbittorrent
    qpwgraph
    quickshell
    pkgs-stable.qtemu
    satty
    scarab
    selectdefaultapplication
    shotcut
    slurp
    smplayer
    solaar
    sysbench
    themechanger
    thunderbird
    tofi
    waypaper
    wofi
    vesktop
    vivaldi
    vivaldi-ffmpeg-codecs
    vlc
    vscodium
    waybar
    zen-browser.packages."${stdenv.hostPlatform.system}".default
    # zed.packages.${stdenv.hostPlatform.system}.default
    zed-editor
  ];
}
