{
  zen-browser,
  pkgs,
  pkgs-stable,
  ...
}:

{
  environment.systemPackages = with pkgs; [
    pkgs-stable.bitwarden-desktop
    # pkgs-stable.m32edit
    pkgs-stable.protonup-qt
    pkgs-stable.unityhub
    anyrun
    audacity
    bitmagnet
    blender
    blueman
    brave
    cider-2
    davinci-resolve
    dconf-editor
    dunst
    flameshot
    furmark
    fuzzel
    gammastep
    ghostty
    gimp
    github-desktop
    gnome-tweaks
    gparted
    grim
    guake
    handbrake
    haruna
    helvum
    heroic
    kdePackages.ark
    kdePackages.dolphin
    kdePackages.filelight
    kdePackages.kate
    kdePackages.okular
    libreoffice-qt6-fresh
    lutris
    lxqt.pavucontrol-qt
    nautilus
    nextcloud-client
    obs-studio
    obs-studio-plugins.wlrobs
    obsidian
    octaveFull
    onedrive
    openrgb-with-all-plugins
    pavucontrol
    phoronix-test-suite
    pinta
    (prismlauncher.override {
      jdks = [
        jdk8
        jdk17
        jdk21
        temurin-bin-8
        temurin-bin-17
        temurin-bin-21
        pkgs.zulu25
      ];
    })
    qbittorrent
    qpwgraph
    quickshell
    satty
    scarab
    selectdefaultapplication
    shotcut
    slurp
    smplayer
    solaar
    sysbench
    themechanger
    thunderbird
    tofi
    waypaper
    wofi
    vesktop
    vivaldi
    vivaldi-ffmpeg-codecs
    vlc
    vscodium
    waybar
    zen-browser.packages."${stdenv.hostPlatform.system}".beta
  ];
}
