{
  pkgs,
  ...
}:

{
  environment.systemPackages = with pkgs; [
    brotli
    bzip3
    corefonts
    freetype
    gdb
    ghostscript
    ghostscriptX
    glib
    gradle
    gvfs
    helvetica-neue-lt-std
    jansson
    libcamera
    logiops
    libinput
    libva-utils
    libvdpau-va-gl
    mesa
    mesa-demos
    netcat-gnu
    openrazer-daemon
    qtcreator
    qt5.full
    kdePackages.qtdeclarative
    redlib
    steam-devices-udev-rules
    tbb
    tk
    vaapiVdpau
    vkbasalt
    vulkan-loader
    vulkan-tools
    vulkan-validation-layers
    wayland-scanner
    wine
    wineWowPackages.stable
    winetricks
    xorg.libxcb
    xorg.libXcursor
    xorg.libXext
    xorg.libXi
    xorg.libXrandr
    xorg.libXrender
    xorg.libXxf86vm
    xorg.libXtst
    xorg.libX11
    xz
    zlib
  ];
}
