return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "clang-format",
      "clangd",
      "cmakelang",
      "cmakelint",
      "codelldb",
      "eslint-lsp",
      "js-debug-adapter",
      "json-lsp",
      "matlab-language-server",
      "ruff",
      "rust-analyzer",
      "shellcheck",
      "shfmt",
      "taplo",
      "texlab",
      "typescript-language-server",
      "vtsls",
      "yaml-language-server",
    },
  },
}
