return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "css",
        "dart",
        "gdscript",
        "go",
        "godot_resource",
        "gdscript",
        "gdshader",
        "html",
        "javascript",
        "json",
        "just",
        "latex",
        "markdown",
        "markdown_inline",
        "matlab",
        "nix",
        "python",
        "qmljs",
        "query",
        "regex",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "yaml",
      },
    },
  },
}
